name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 7.1, 7.2, 7.3, 7.4 ]

    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Build image
      run: |
        docker build --pull -t kooldev/wordpress:${{ matrix.version }} ${{ matrix.version }}
        docker build -t kooldev/wordpress:${{ matrix.version }}-nginx ${{ matrix.version }}-nginx

    - name: Test docker images PHP executable
      run: |
        docker run kooldev/wordpress:${{ matrix.version }} php -v
        docker run kooldev/wordpress:${{ matrix.version }}-nginx php -v

    - name: Test docker images wordpress code
      run: |
        docker run kooldev/wordpress:${{ matrix.version }} php /usr/src/wordpress/index.php
        docker run kooldev/wordpress:${{ matrix.version }}-nginx php /usr/src/wordpress/index.php

    - name: Push to Hub
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push kooldev/wordpress:${{ matrix.version }}
        docker push kooldev/wordpress:${{ matrix.version }}-nginx
